var array = [1, 2, 3, 4, 5];
var [] = array;
var a1 = array[0],
    b1 = array[1];
var a2 = array[0],
    b2 = array[2];
var a3 = array[0] === undefined ? aDefault : array[0],
    b3 = array[1];
var a4 = array[0],
    b4 = array[1],
    rest1 = array.slice(2);
var a5 = array[0],
    b5 = array[2],
    rest2 = array.slice(3);
var [a7, b7, ...[c7, d7]] = array;
var _a = getValue(),
    a = _a[0],
    b = _a[1];
var _a2 = [1, 2, 3],
    a11 = _a2[0],
    b11 = _a2[1];
var a22 = array[0],
    b22 = array[1];
var _a3 = schemaProperties('properties'),
    allProps = _a3[0],
    properties = _a3[1],
    _a4 = schemaProperties('optionalProperties'),
    allOptProps = _a4[0],
    optProperties = _a4[1];